/*
 * Copyright 2009 Martin Brentnall
 *
 * This file is part of Iso-Realms.
 *
 * Iso-Realms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Iso-Realms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Iso-Realms.  If not, see <http://www.gnu.org/licenses/>.
 */
#ifndef I_ELEMENT_GATEWAY_H
#define I_ELEMENT_GATEWAY_H

#include "IElement.h"
#include "IElementContainer.h"

class Zone;

/**
 * This interface should be implemented by editing component wishing to recieve
 * elements generated by an IElementFactory.
 */
class IElementGateway {
  public:
  virtual ~IElementGateway() {}

  /**
   * Push the specified element through the gateway and into the current zone.
   * 
   * @param IElement*  The element to push.
   */
  virtual IElementContainer* pushElement(IElement*) = 0;

  /**
   * Push the specified element through the gateway and into the map (i.e. not
   * confined to a specific zone).
   * 
   * @param IElement*  The element to push.
   */
  virtual IElementContainer* pushMapElement(IElement*) = 0;

  /**
   * Notify the pending destruction of the specified element.  When this is
   * called, the client should ensure that the specified element is referenced
   * any more.
   * 
   * @param IElement*  The element that will be destroyed.
   * @returns The Zone that the element was in.
   */
  virtual IElementContainer* notifyDestruction(IElement*) = 0;
};

#endif
