# Copyright 2009 Martin Brentnall
#
# This file is part of Iso-Realms.
#
# Iso-Realms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Iso-Realms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Iso-Realms.  If not, see <http://www.gnu.org/licenses/>.
objs:
	cd 3DModel; make
	cd Camera; make
	cd Collectables; make
	cd CollidableSurfaceRegistry; make
	cd CommandRegistry; make
	cd FourColourSupport; make
	cd IntegerValue; make
	cd LocationAwareness; make
	cd SoundSupport; make
	cd SpindizzyTextureSet; make
	cd SpindizzyTextureSetChanger; make
	cd SurfaceProcessor; make
	cd Utilities; make
	cd ZoneContext; make

clean:
	cd 3DModel; make clean
	cd Camera; make clean
	cd Collectables; make clean
	cd CollidableSurfaceRegistry; make clean
	cd CommandRegistry; make clean
	cd FourColourSupport; make clean
	cd IntegerValue; make clean
	cd LocationAwareness; make clean
	cd SoundSupport; make clean
	cd SpindizzyTextureSet; make clean
	cd SpindizzyTextureSetChanger; make clean
	cd SurfaceProcessor; make clean
	cd Utilities; make clean
	cd ZoneContext; make clean

all:
	make clean
	make objs

